version: "3.7"
services:

    app:
        container_name: app-gauge-message
        build:
            args:
                user: gauge
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - api-extension-gauge


    nginx:
        container_name: nginx-gauge-message
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8180:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - api-extension-gauge

    mysql:
        container_name: db-gauge-message
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3388:3306
        networks:
            - api-extension-gauge

networks:
    api-extension-gauge:
        driver: bridge
